# Generated by Django 4.2.3 on 2023-07-11 14:47

import django.core.validators
from django.db import migrations, models
import pages.validates
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Philanthropist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_pics', models.ImageField(upload_to='philanthropist/displayPics', validators=[pages.validates.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('prep_profile_descriptions', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('profile_descriptions', tinymce.models.HTMLField()),
                ('others_right_side_profile', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Philanthropist',
                'verbose_name_plural': 'Philanthropists',
            },
        ),
        migrations.CreateModel(
            name='ReadOurNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('anchor_link', models.CharField(max_length=400)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Read Our New',
                'verbose_name_plural': 'Read Our News',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('display_pic', models.ImageField(default='', upload_to='testimony/displayPics/', validators=[pages.validates.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Testimonies',
                'verbose_name_plural': 'Testimonies',
            },
        ),
    ]
