# Generated by Django 4.2.3 on 2023-07-18 10:35

import django.core.validators
from django.db import migrations, models
import pages.validates


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readournew',
            name='news_display_pic',
            field=models.ImageField(default='', upload_to='readournews/displayPics/', validators=[pages.validates.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='readournew',
            name='anchor_link',
            field=models.CharField(max_length=1000),
        ),
    ]
