# Generated by Django 4.2.3 on 2023-07-18 10:38

import django.core.validators
from django.db import migrations, models
import pages.validates


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_readournew_news_display_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philanthropist',
            name='display_pics',
            field=models.ImageField(blank=True, null=True, upload_to='philanthropist/displayPics', validators=[pages.validates.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='readournew',
            name='news_display_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='readournews/displayPics/', validators=[pages.validates.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, upload_to='testimony/displayPics/', validators=[pages.validates.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
